# Generated by Django 3.1.7 on 2021-03-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('max_enrl_blk', models.IntegerField()),
                ('min_enrl_blk', models.IntegerField()),
                ('prep_time_hours_blk', models.FloatField()),
                ('security_class_id', models.CharField(max_length=10)),
                ('block_number', models.CharField(max_length=2)),
                ('block_desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=1000)),
                ('evaluation', models.CharField(max_length=1000)),
                ('inst_guidance', models.CharField(max_length=1000)),
                ('objective_hours', models.FloatField()),
                ('unit_number', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.CharField(max_length=2000)),
                ('task_number', models.IntegerField()),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('unit_description', models.CharField(max_length=256)),
            ],
        ),
    ]
